### ISSUE TITLE
DL-for-LULC-prediction

### ISSUE THREAD

**Issue by zafor44** [iamtekson/DL-for-LULC-prediction#1]
Sir
how could we prepare the data set like eurosat?

**Comment by iamtekson** [comment]
For preparing such data, you need to download the various optical satellite imagery, make tiles and need to create different folders for different classes.

**Comment by zafor44** [comment]
Would you please make a short tutorial or a code for me. I am stacked at this point.
Thanks and regards

**Comment by zafor44** [comment]
NameError: name 'cm' is not defined
OSError: No file or directory found at lulc

**Comment by iamtekson** [comment]
You need to run the code from top to bottom (All the cells in correct order). 

Regarding the tutorial, I will create it, but it might take some time for me.
