### ISSUE TITLE
Pretrained weights file

### ISSUE THREAD

**Issue by gokhanakcay** [iamtekson/DL-for-LULC-prediction#2]
Could you please provide your trained Resnet-50 model weights as a .h5 file?

**Comment by iamtekson** [comment]
Hi, Sorry for the late reply. Please click [this link](https://github.com/iamtekson/deep-learning-for-earth-observation/raw/main/Notebooks/01.%20image-classification/model/model_100_epoch.h5) to download the pre-trained weight.
